In [5]:
import pandas as pd

products = pd.read_parquet("../data/raw/products.parquet")
countries = pd.read_parquet("../data/raw/countries.parquet")
sales_orders = pd.read_parquet("../data/raw/sales_orders.parquet")
order_lines = pd.read_parquet("../data/raw/order_lines.parquet")
CRM = pd.read_parquet("../data/raw/CRM.parquet")


def convert_numeric_columns(data, ignore=[]):
    for column in data.columns:
        if column not in ignore and not pd.api.types.is_object_dtype(data[column]):
            try:
                data[column] = pd.to_numeric(data[column], errors="coerce")  
            except Exception as e:
                print(f"‚ö†Ô∏è No se pudo convertir '{column}': {e}")

    return data

convert_numeric_columns(data=products)
convert_numeric_columns(data=countries)
convert_numeric_columns(data=sales_orders, ignore=["date_order"])
convert_numeric_columns(data=order_lines)
convert_numeric_columns(data=CRM)

sales_orders["date_order"] = pd.to_datetime(sales_orders["date_order"], errors="coerce")


print("\nüìå Datasets Dtypes:")
print("\n Products:")
print(products.dtypes)
print("\n Countries:")
print(countries.dtypes)
print("\n Sales orders:")
print(sales_orders.dtypes)
print("\n Order lines:")
print(order_lines.dtypes)
print("\n CRM:")
print(CRM.dtypes)

üìå Datasets Dtypes:

 Products:
id              int64
name           object
category       object
image_route    object
dtype: object

 Countries:
id       int64
code    object
name    object
dtype: object

 Sales orders:
order_id                    object
partner_invoice             object
partner_shipping            object
date_order          datetime64[ns]
state                       object
amount_untaxed             float64
amount_tax                 float64
amount_total               float64
country_code                object
dtype: object

 Order lines:
id               object
order_id         object
product_name     object
quantity        float64
unit_price      float64
subtotal        float64
dtype: object

 CRM:
lead_id          int64
name            object
email_from      object
phone           object
stage           object
contact_name    object
image_html      object
dtype: object

In [6]:
def fill_numeric_columns(data, ignore=[]):
    for column in data.columns:
        if column not in ignore and not pd.api.types.is_object_dtype(data[column]):
            try:
                # datos de ventas pueden ser facilmente rellnados con 0 si no estan
                data[column] = data[column].fillna(0) 
            except Exception as e:
                print(f"‚ö†Ô∏è No se pudo rellenar '{column}': {e}")

    return data

fill_numeric_columns(data=products)
fill_numeric_columns(data=countries)
fill_numeric_columns(data=sales_orders, ignore=["date_order"])
fill_numeric_columns(data=order_lines)
fill_numeric_columns(data=CRM)

sales_orders["date_order"] = sales_orders["date_order"].fillna("ffill")

In [7]:
CRM = CRM.drop("image_html", axis=1)
products = products.drop("image_route", axis=1)
products.drop_duplicates(inplace=True)
countries.drop_duplicates(inplace=True)
sales_orders.drop_duplicates(inplace=True)

In [8]:
def convert_object_lowercase(data, ignore=[]):
    for column in data.columns:
        if column not in ignore and pd.api.types.is_object_dtype(data[column]):
            try:
                data[column] =  data[column].fillna("").str.lower().str.strip()
            except Exception as e:
                print(f"‚ö†Ô∏è No se pudo convertir '{column}': {e}")

    return data

convert_object_lowercase(data=products)
convert_object_lowercase(data=countries)
convert_object_lowercase(data=sales_orders, ignore=["date_order"])
convert_object_lowercase(data=order_lines)
convert_object_lowercase(data=CRM)

print("\nüìå Primeros registros de cada dataset:")
print("\n Products")
print(products.head())
print("\n Countries")
print(countries.head())
print("\n Sales orders")
print(sales_orders.head())
print("\n Order lines")
print(order_lines.head())
print("\n CRM")
print(CRM.head())

üìå Primeros registros de cada dataset:

 Products
   id                                    name     category
0   5                           communication          all
1   7                       standard delivery   deliveries
2   6                                expenses     expenses
3  12  audifonos argom bluetooth arg-hs-2552b  electronics
4   1                                   meals          all

 Countries
   id code            name
0   3   af     afghanistan
1   6   al         albania
2  62   dz         algeria
3  11   as  american samoa
4   1   ad         andorra

 Sales orders
  order_id   partner_invoice    partner_shipping          date_order state  \
0   s00051    lilianna perez  harvard university 2025-01-29 00:23:15  sale
1   s00050     milena garcia           microsoft 2025-01-28 21:39:34  sale
2   s00049     jordana alphy  harvard university 2025-01-28 21:39:00  sale
3   s00048  humberto marcebo           microsoft 2025-01-28 21:38:35  sale
4   s00047  humberto marcebo           microsoft 2025-01-28 21:38:08  sale

   amount_untaxed  amount_tax  amount_total country_code
0         26995.0      4859.1       31854.1           cr
1          1235.0       179.1        1414.1           fr
2         27193.0      4859.1       32052.1           al
3         54990.0      9898.2       64888.2           pe
4         26995.0      4859.1       31854.1           pe

 Order lines
                                     id order_id  \
0  f12dbcd1-e2d0-47a0-b320-a7f61be2fc9d   s00051
1  abeb05a7-f00a-4da3-b473-62f042b24d0f   s00050
2  947cf4ca-f16a-4580-a33f-a64b6272329b   s00050
3  4d0ba4b1-35ad-4155-83fb-19ad272e624e   s00049
4  6a5685ca-4aa7-45e4-a7c0-14ba69a65421   s00049

                                 product_name  quantity  unit_price  subtotal
0  celular samsung a35 256gb negro 356ezkggto       1.0     26995.0   26995.0
1                   sandwichera nikkei 264124       1.0       995.0     995.0
2                    pan sobao buenhorno 10/1       4.0        60.0     240.0
3  celular samsung a35 256gb negro 356ezkggto       1.0     26995.0   26995.0
4         galletas dulces oreo regular 12 und       1.0       198.0     198.0

 CRM
   lead_id                          name            email_from       phone  \
0       11  lilianna perez's opportunity    lilperez@gmail.com  8296452222
1        9           lenny manuel garcia  lennymgr27@gmail.com  8296579686
2        3  lunch supplier's opportunity     luncher@gmail.com  8298599543
3        8     mylan ramos's opportunity      mylanr@gmail.com  8296572014
4        6   jordana alphy's opportunity    jordanlp@gmail.com  8295473692

       stage    contact_name
0  qualified  lilianna perez
1        new   administrator
2        won  lunch supplier
3  qualified     mylan ramos
4  qualified   jordana alphy

In [9]:
products.to_parquet("../data/processed/products.parquet")
countries.to_parquet("../data/processed/countries.parquet")
sales_orders.to_parquet("../data/processed/sales_orders.parquet")
order_lines.to_parquet("../data/processed/order_lines.parquet")
CRM.to_parquet("../data/processed/CRM.parquet")